name: build-production

on: 
  push:
    branches: 
      - production

jobs:
  build-staging:
    runs-on: ubuntu-latest

    env:
      DEPLOY_ENV: production

    steps:
      - uses: actions/checkout@v2
        with:
          ref: production

      - uses: actions/setup-node@v1

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - run: npm install    

      - run: npm build
        
      - uses: actions-hub/gcloud@master
        env:
          PROJECT_ID: focusproject-105105
          APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        with:
          args: rsync -R build gs://todo.mospcorp.com
          cli: gsutil
