name: build-production

on: 
  push:
    branches: 
      - production

jobs:
  build-staging:
    runs-on: ubuntu-latest

    env:
      DEPLOY_ENV: production
      # add secrets from cloud provider XXX: ${{ secrets.XXX  }}

    steps:
      - uses: actions/checkout@v2
        with:
          ref: production

      - uses: actions/setup-node@v1

      # - run: install app from cloud provider to deploy

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - run: npm install    

      - run: npm build
        
      # - run: deploy somewhere
