name: build-staging

on: 
  push:
    branches: 
      - master

jobs:
  build-staging:
    runs-on: ubuntu-latest

    env:
      DEPLOY_ENV: staging

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - run: npm install    

      - run: npm test --watchAll=false
